---
title: "Climate Conditions and Flooding Disasters in Nova Scotia"
subtitle: "Data Analysis STAT 4620/5620 Winter 24-25"
author: "Kyle Allie, Thu Nguyen, Margo Paris, Fatma Sarhan"
date: today
date-format: "YYYY-MM-DD"
format: 
  pdf:
    toc: false  
    latex_engine: xelatex 
editor: source
header-includes:
  - \usepackage{hyperref}
  - \usepackage{graphicx}  
bibliography: ../References/citations.bib 
---
\begin{center}
  \vspace{-5mm}
    \href{https://github.com/KyleA2001/STAT4620\_5620-Flooding\_Project.git}{ https://github.com/KyleA2001/STAT4620\_5620-Flooding\_Project.git}
\end{center}

\newpage

# Abstract

Summary in 150 words (Best done last, summarizes the whole project)

# Keywords (max 10)

- Storm Surge
- Generalized Additive Mixed Models (GAMM)
- Time Series
- Autocorrelation Function (ACF)
- Cross-Correlation Function (CCF)

# Introduction

Over the past decade, Nova Scotia has experienced an increasing number of flooding events resulting from thunderstorms, heavy rain, and extreme weather conditions. These events have significantly impacted communities, resulting in evacuations, property damage, infrastructure loss, and loss of life. The province's geographic location along the Atlantic Ocean and its coastal regions make Nova Scotia vulnerable to these events. As the frequency and severity of extreme weather conditions continue to rise due to climate change, there has been an growing interest to study how various climatic factors are related to these flooding events. 

One of the most significant components involved with flooding is storm surge, the sudden rise in water level which is created by both the water level and the tide height. Storm Surge can be derived using the difference from the observed water level and the fitted tide values. In this study, the observed water level data were obtained from the Government of Canada Data Archives, while the fitted tide values were calculated using the R package "ftide." Using both these values, the storm surge response variable was derived, which is used to explore which climatic factors are most closely associated with storm surge.

Modeling these extreme weather events can be challenging due to their rarity and the complex way multiple climatic factors may interact.  Although flooding events are relatively infrequent, their impact can cause Significant societal and economic damage, highlighting the need for improved forecasting tools.  This research seeks to understand the relationship between various climatic factors and storm surge levels at selected locations across Nova Scotia. A secondary objective is to use these findings to forecast the likelihood of future flooding events based on the most significant contributing climatic factors.

This research will address two key questions:

1.  What is the relationship between various climatic factors and storm surge levels across Nova Scotia?

2.  How can the most significant correlated factors be used to predict future flooding catastrophes in Nova Scotia?

Through these investigations, this study aims to contribute valuable predictions and  insights that will aid in understanding, and reducing future flooding risks in the province.

# Data Description

In this section, we describe the data used for the analysis. Below is the summary table for the data obtained from the Government of Canada:

```{=latex}
\begin{table}[h]
\centering
\resizebox{\textwidth}{!}{ % Resizes the table to fit the width of the page
\begin{tabular}{|c|c|c|c|}
\hline
\textbf{Variables} & \textbf{Units} & \textbf{Description} & \textbf{Frequency} \\
\hline
Date & days & Date when data was recorded & Daily \\
Location & & Halifax and Yarmouth &  \\
Water Level & m (meters) & Height above datum or reference system & Hourly \\
Storm Surge & m (meters) & Water rise due to water level and tide height & Hourly \\
Air Temperature & °C & Air temperature & Daily min/max, Hourly avg \\
Wind Speed & km/h & Wind speed & Daily min/max, Hourly avg \\
Rainfall & mm & Precipitation (not including snow) & Real daily value \\
\hline
\end{tabular}
}
\caption{Data description summary}
\end{table}
```

The following covariates will be used in the model: air temperature, rain, and wind speed. These variables were selected because of their potential to influence storm surge levels, with each factor known to play a role in flood behavior. The goal is to fit these covariates into a model to determine whether any of them can significantly predict the response variable, storm surge. 

Various covariates were considered for inclusion in the model, given the potential influence of multiple climatic factors on storm surge. However, including too many variables could result in overfitting, where the model captures noise rather than meaningful patterns, leading to inaccurate predictions. To avoid this, a simpler approach was taken by narrowing down the key variables that have the strongest observed relationships with storm surge.

One way flooding can occur is through heavy rainfall, which is one of the most significant factors in causing floods. If the amount of water from rain rises faster than it can return to the ocean or be absorbed by the soil, this leads to flooding. Given its significant impact on flood events, rainfall was chosen as a key variable in this study.

Rainfall itself is influenced by many factors, but one primary factor is air temperature. As temperatures rise, the atmosphere's ability to hold moisture increases, leading to greater rainfall amounts. Air temperature is one of the leading meteorological factors that interacts with heavy storms[@AirTemperature]. Therefore, it is important that air temperature is considered when examining storm surge.

Finally, wind speed was considered an important variable based because wind can increase flood magnitudes, durations, and spatial extents[@Windspeed]. This highlights the significant role that wind plays in the intensity and reach of flooding events, especially along coastal regions. Given that Nova Scotia is a coastal province, the impact of wind on flood events is particularly relevant. Thus, wind speed was included in this study as a critical climatic factor to understand its contribution to storm surge and flooding, especially in combination with other factors like rainfall and air temperature. 

Overall, these three covarites were decided to use in the study with storm surge due to their importance, and creating a simpler model. 


Storm surge is a critical value in flood and storm impact analysis, but it cannot be directly observed. Instead, it must be calculated using the following formula:

$$
\text{Storm Surge} = \text{Observed Water Level} - \text{Fitted Tide}
$$
The observed water level is obtained from archived data provided by the Government of Canada. This data was measured at two separate locations: Halifax and Yarmouth.

The fitted tide uses the function ftide, where it fits the tidal data using any set of harmonic constiuents. This function takes in three main components:

- x: A numeric vector object giving the water levels; it allows for missing values.

- dto: A date vector of same length as ’x’ which should be a POSIXct object; it does
not allow for missing values.

- hcn: A vector of constituent names. Here, we specify only the 4 major harmonic
constituents, hc4.

By applying this function to the observed water levels, the predicted storm surge values can be calculated. This function allows for the accurate estimation of storm surge at the specified locations based on tide and observations water levels.

# Methods

– Provide a brief description of the analytical tools you will used 
– Discuss why the method is appropriate in the context of the research question and the data, including any assumptions required by the method.

During the initial start of the project, a various amount of methods were brought up. It was decided that the two main methods to answer question 1 of the research would be GLMs and Time Series. GLMs were considered because it would help provided a baseline to figure out what factors affect tidal storm surge. Unfortunately, there were some limitations and violated assumptions that prevented the use of this model.

Generalized Linear Models (GLMs) are a traditional linear regression that handles a wider range of data types (Continuous, count, etc...). What this model does not account for is the limitations of time-dependent data. The data collected in this research depends on the time it was collected, to find a relationship with storm surge and use for future prediction. Without the use of time data in the model, their will not be any acurate predictions.

An assumption that GLMs have is that all observations are independent. However, the data collected violates this assumption because the observations are dependent on time, meaning that values recorded at one time point are likely influenced by previous observations. This temporal dependency introduces autocorrelation, where data points closer in time are more similar, making GLMs less suitable for capturing these patterns. As a result, applying a method that accounts for time dependence was necessary to better model the data.

The dependence on time lead to the use of GAMMs (Generalized Additive Mixed Models). Generalized Additive Models (GAMs) are a versatile statistical modeling technique used to analyze complex relationships within data. Unlike linear models, GAMs can capture non-linear patterns by combining multiple smooth functions of predictor variables[@GAMM]. The model does not account for time dependence or correlated observations. This is where the model choice extends to GAMMs that accounts for both. 

GAMMs assume that the random effects are independent. Since the data collected is from two different locations, the random effect from each location should be independent from each other. Another assumption is that Storm Surge should be able to follow a certain distribution. For the research the assumption is that the model follows a Normal Distribution. One of the important assumptions is temporal correlation, where observations in the past influence future values. The random effect to the model accounts for this.

(Insert code for acf)

ACF (Autocorrelation Function) is a method that will show how much a a variable at one time is related to its value at previous times. Since the research is studying storm surge, ACF will show if today's storm surge value was influenced from its values yesterday, before than, etc... ACF helps identity any patterns in the time series data, like seasonality or trends. If the current and past value show to be highly correlated, then the data is not random and there is some predictability in the structure. 
Using ACF on the GAMM model, their is high correlation between the data points, suggesting that the data collected for each time are dependent. This violates the assumption of GAMMs, and therefore makes it unusable for the model. 

The other model that will be used for this analysis is Time Series. Time Series models the sequence of data points in an equally spaced time interval. The method is used to analyze trends, patterns, and behaviours over time. The importance of this model is to analyze historical data to help understand any underlying patterns, predict future values, and see how (or if any for out research) certain factors influence storm surge over time. 

The goal of the research is to see what climatic factors affect storm surge over time. Time series modeling will help examine if these variables have a time-based relationship with storm surge. GAMMs was helpful for modeling non-linear, time-dependent relationships between the predictors and the response variable. However, it might not accurately represent the complex nature of time series data.

Time Series models assume that the data is stationary and no autocorrelation in the residuals. (Unsure what else to add)

Since the research analyzes storm sure data, ACF will help look at temporal dependencies. This will help identify how much past climatic factors influences storm surges behaviour. 

CCF(Cross-Correlation Function) is the same as ACF, but instead examines the relationship between two different time series, with more flexibility to look at different points in time. When using CCF for the model, it is testing how strongly the response variable (Storm Surge) is related to another variable (predictor variables like rain, wind speed, and temperature) over different lags. For the research, CCF can help to see if rain, wind speed, and/or temperature have an immediate or delayed effect on storm surge. 

VAR(Vector Auto regression) (not 100% about this model)

Granger Causality (Not 100% sure)


Question 2's method is missing....


# Analysis

– Show the code used to actually apply the methods to the data. – Include model validation.

Bring over code 

# Results

– Present and discuss the outputs of your methods. 
– Include any visualizations of the analysis.

Bring over code 

# Conclusions

– Discuss the results of the previous section in the context of the research question. – Give an answer to your research question and discuss any uncertainty in your results. – If appropriate, discuss why the research question cannot be fully answered using the data and techniques available.

# References

– Cite data sources. –

Cite literature and other sources useful for explaining the background information, research question, and analytical tools.

